### ISSUE TITLE
Comparison to Yukaii/synchronized-promise

### ISSUE THREAD

**Issue by papb** [Richienb/p-sync#2]
Hello! Is there any important difference between this module and https://github.com/Yukaii/synchronized-promise? Thanks.

**Comment by Richienb** [comment]
@papb Instead of manually imposing `deasync.sleep`, this module uses `deasync`'s built-in callback awaiting system. Whilst the functionality of both of these packages are very similar, the actual implementation varies.

**Comment by papb** [comment]
Thanks!
